### ISSUE TITLE
Call to undesired IP

### ISSUE THREAD

**Issue by EBendinelli** [vanita5/mastodon-api#13]
Hello there,

Thank you for this API. I'm using [Yogthos' mastodon-bot](https://github.com/yogthos/mastodon-bot) in a very tigh and controled environment.

The bot has been working very well but has recently begun to make call to an undesired IP address. After some research, this seems to be occuring when using [mastodon-api ](https://github.com/yogthos/mastodon-bot/blob/master/mastodon-bot.cljs#L122). I'm requesting this profile https://mastodon.xyz/web/accounts/257584 and it results in (among other things) a call to this IP address which is in no way linked or appear on this profile: 163.172.251.107

I unfortunately don't have time to investigate why this is happening so if anyone had an idea I'll be happy to hear it as it quite problematic within my tighly controled environment.

**Comment by vanita5** [comment]
Hey,

this is just the IP address mastodon.xyz resolves to.

```bash
$ ping mastodon.xyz
PING mastodon.xyz (163.172.251.107) 56(84) bytes of data.
```

**Comment by EBendinelli** [comment]
...

That'll teach me not to curl, my iptables rules where missing mastodon.xyz
Thanks for the support!
