### ISSUE TITLE
Failed to use streaming/user using js

### ISSUE THREAD

**Issue by dru18** [vanita5/mastodon-api#14]
I'm trying to use GET /api/v1/streaming/user

but Failed to  use streaming/user using js

### Expected behaviour

that should have Return events that are relevant to the authorized user, i.e. home timeline and notifications to me

### Actual behaviour

but gave me this error after 5 seconds of hold
https://github.com/dru18/druBot/blob/master/issue/screenshot/error_streaming_user.png
### Steps to reproduce the problem

i'm using this code to get steaming/user
https://github.com/dru18/druBot/blob/master/issue/druStream.js
### Specifications

i'm using
OS: Mint 18.3 sylvia

**Comment by eliah-w** [comment]
From the error it looks like you use an outdated version of node. Make sure to use node v6.0.0 or higher.
