### ISSUE TITLE
TransformError on React Native

### ISSUE THREAD

**Issue by deguchi** [vanita5/mastodon-api#2]
Hello, Thank you for nice library.

I met TransformError on React Native.

**Environment:**
Mac OSX 10.12.4
node v7.7.1
React Native 0.43
https://facebook.github.io/react-native/docs/getting-started.html

import Mastodon from 'mastodon-api'

![GitHub Logo](https://yabumi.cc/15bc1d432479098319b0bc9a.png)

I tried to use Babel Latest preset and set "latest" to .babelrc.
but Error Message not changed.
[https://babeljs.io/docs/plugins/preset-latest/](https://babeljs.io/docs/plugins/preset-latest/)

Please tell me any solution?
Thanks!

**Comment by vanita5** [comment]
Thanks for your report.
I forgot to add my .babelrc to .npmignore. This should fix the error.
